// A large curated database of motivational quotes for the top-bar ticker.
// `a` (author) is null for anonymous sayings / proverbs. Kept as plain data so
// it's trivial to extend — just add more { t, a } entries.

export interface Quote {
  t: string; // the quote text
  a: string | null; // author, or null when unknown
}

export const QUOTES: Quote[] = [
  { t: "Whether you think you can, or you think you can't — you're right.", a: "Henry Ford" },
  { t: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { t: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { t: "Success is not final, failure is not fatal: it is the courage to continue that counts.", a: "Winston Churchill" },
  { t: "Believe you can and you're halfway there.", a: "Theodore Roosevelt" },
  { t: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { t: "Don't watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
  { t: "The secret of getting ahead is getting started.", a: "Mark Twain" },
  { t: "Quality is not an act, it is a habit.", a: "Aristotle" },
  { t: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Will Durant" },
  { t: "The journey of a thousand miles begins with a single step.", a: "Lao Tzu" },
  { t: "Fall seven times, stand up eight.", a: "Japanese Proverb" },
  { t: "What you get by achieving your goals is not as important as what you become by achieving them.", a: "Zig Ziglar" },
  { t: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "C.S. Lewis" },
  { t: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
  { t: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { t: "If you want to lift yourself up, lift up someone else.", a: "Booker T. Washington" },
  { t: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
  { t: "Everything you've ever wanted is on the other side of fear.", a: "George Addair" },
  { t: "The man who moves a mountain begins by carrying away small stones.", a: "Confucius" },
  { t: "Act as if what you do makes a difference. It does.", a: "William James" },
  { t: "Success usually comes to those who are too busy to be looking for it.", a: "Henry David Thoreau" },
  { t: "Don't be afraid to give up the good to go for the great.", a: "John D. Rockefeller" },
  { t: "I find that the harder I work, the more luck I seem to have.", a: "Thomas Jefferson" },
  { t: "Opportunities don't happen. You create them.", a: "Chris Grosser" },
  { t: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt" },
  { t: "Success is walking from failure to failure with no loss of enthusiasm.", a: "Winston Churchill" },
  { t: "Little by little, one travels far.", a: "J.R.R. Tolkien" },
  { t: "The only limit to our realization of tomorrow will be our doubts of today.", a: "Franklin D. Roosevelt" },
  { t: "It is never too late to be what you might have been.", a: "George Eliot" },
  { t: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe" },
  { t: "You miss 100% of the shots you don't take.", a: "Wayne Gretzky" },
  { t: "Whatever you are, be a good one.", a: "Abraham Lincoln" },
  { t: "The best revenge is massive success.", a: "Frank Sinatra" },
  { t: "A year from now you may wish you had started today.", a: "Karen Lamb" },
  { t: "The harder the conflict, the greater the triumph.", a: "George Washington" },
  { t: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn" },
  { t: "Either you run the day or the day runs you.", a: "Jim Rohn" },
  { t: "If you are not willing to risk the usual, you will have to settle for the ordinary.", a: "Jim Rohn" },
  { t: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Rohn" },
  { t: "Don't wish it were easier; wish you were better.", a: "Jim Rohn" },
  { t: "We must all suffer one of two things: the pain of discipline or the pain of regret.", a: "Jim Rohn" },
  { t: "The successful warrior is the average man, with laser-like focus.", a: "Bruce Lee" },
  { t: "As you think, so shall you become.", a: "Bruce Lee" },
  { t: "Do not pray for an easy life, pray for the strength to endure a difficult one.", a: "Bruce Lee" },
  { t: "Knowing is not enough, we must apply. Willing is not enough, we must do.", a: "Bruce Lee" },
  { t: "If you spend too much time thinking about a thing, you'll never get it done.", a: "Bruce Lee" },
  { t: "The mind is everything. What you think you become.", a: "Buddha" },
  { t: "It is better to conquer yourself than to win a thousand battles.", a: "Buddha" },
  { t: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", a: "Buddha" },
  { t: "What we think, we become.", a: "Buddha" },
  { t: "The best way to predict the future is to create it.", a: "Peter Drucker" },
  { t: "Well done is better than well said.", a: "Benjamin Franklin" },
  { t: "By failing to prepare, you are preparing to fail.", a: "Benjamin Franklin" },
  { t: "Energy and persistence conquer all things.", a: "Benjamin Franklin" },
  { t: "An investment in knowledge pays the best interest.", a: "Benjamin Franklin" },
  { t: "Lost time is never found again.", a: "Benjamin Franklin" },
  { t: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison" },
  { t: "I have not failed. I've just found 10,000 ways that won't work.", a: "Thomas Edison" },
  { t: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", a: "Thomas Edison" },
  { t: "There is no substitute for hard work.", a: "Thomas Edison" },
  { t: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", a: "Thomas Edison" },
  { t: "If you can dream it, you can do it.", a: "Walt Disney" },
  { t: "The way to get started is to quit talking and begin doing.", a: "Walt Disney" },
  { t: "All our dreams can come true, if we have the courage to pursue them.", a: "Walt Disney" },
  { t: "Try not to become a man of success, but rather try to become a man of value.", a: "Albert Einstein" },
  { t: "In the middle of difficulty lies opportunity.", a: "Albert Einstein" },
  { t: "Life is like riding a bicycle. To keep your balance you must keep moving.", a: "Albert Einstein" },
  { t: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },
  { t: "Strive not to be a success, but rather to be of value.", a: "Albert Einstein" },
  { t: "Imagination is more important than knowledge.", a: "Albert Einstein" },
  { t: "You have to expect things of yourself before you can do them.", a: "Michael Jordan" },
  { t: "I've failed over and over and over again in my life. And that is why I succeed.", a: "Michael Jordan" },
  { t: "Some people want it to happen, some wish it would happen, others make it happen.", a: "Michael Jordan" },
  { t: "Obstacles don't have to stop you. If you run into a wall, figure out how to climb it.", a: "Michael Jordan" },
  { t: "Talent wins games, but teamwork and intelligence win championships.", a: "Michael Jordan" },
  { t: "It's not whether you get knocked down; it's whether you get up.", a: "Vince Lombardi" },
  { t: "The difference between a successful person and others is not a lack of strength, but a lack of will.", a: "Vince Lombardi" },
  { t: "Winners never quit and quitters never win.", a: "Vince Lombardi" },
  { t: "Perfection is not attainable, but if we chase perfection we can catch excellence.", a: "Vince Lombardi" },
  { t: "The only place where success comes before work is in the dictionary.", a: "Vidal Sassoon" },
  { t: "Do not wait to strike till the iron is hot; but make it hot by striking.", a: "William Butler Yeats" },
  { t: "Great things are done by a series of small things brought together.", a: "Vincent van Gogh" },
  { t: "I would rather die of passion than of boredom.", a: "Vincent van Gogh" },
  { t: "What would life be if we had no courage to attempt anything?", a: "Vincent van Gogh" },
  { t: "You can't use up creativity. The more you use, the more you have.", a: "Maya Angelou" },
  { t: "If you don't like something, change it. If you can't change it, change your attitude.", a: "Maya Angelou" },
  { t: "Nothing will work unless you do.", a: "Maya Angelou" },
  { t: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", a: "Maya Angelou" },
  { t: "We may encounter many defeats but we must not be defeated.", a: "Maya Angelou" },
  { t: "Courage is the most important of all the virtues, because without courage you can't practice any other virtue consistently.", a: "Maya Angelou" },
  { t: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", a: "Roy T. Bennett" },
  { t: "The only person you are destined to become is the person you decide to be.", a: "Ralph Waldo Emerson" },
  { t: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson" },
  { t: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
  { t: "Once you make a decision, the universe conspires to make it happen.", a: "Ralph Waldo Emerson" },
  { t: "Nothing great was ever achieved without enthusiasm.", a: "Ralph Waldo Emerson" },
  { t: "Write it on your heart that every day is the best day in the year.", a: "Ralph Waldo Emerson" },
  { t: "Dream big and dare to fail.", a: "Norman Vaughan" },
  { t: "Our greatest glory is not in never falling, but in rising every time we fall.", a: "Confucius" },
  { t: "Life is really simple, but we insist on making it complicated.", a: "Confucius" },
  { t: "When it is obvious that the goals cannot be reached, adjust the action steps.", a: "Confucius" },
  { t: "Wherever you go, go with all your heart.", a: "Confucius" },
  { t: "Choose a job you love, and you will never have to work a day in your life.", a: "Confucius" },
  { t: "You are never too old to set another goal or to dream a new dream.", a: "C.S. Lewis" },
  { t: "There are far better things ahead than any we leave behind.", a: "C.S. Lewis" },
  { t: "You can't go back and change the beginning, but you can start where you are and change the ending.", a: "C.S. Lewis" },
  { t: "The greatest glory in living lies not in never falling, but in rising every time we fall.", a: "Nelson Mandela" },
  { t: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", a: "Nelson Mandela" },
  { t: "A winner is a dreamer who never gives up.", a: "Nelson Mandela" },
  { t: "Education is the most powerful weapon which you can use to change the world.", a: "Nelson Mandela" },
  { t: "The greatest weapon against stress is our ability to choose one thought over another.", a: "William James" },
  { t: "Believe that life is worth living and your belief will help create the fact.", a: "William James" },
  { t: "The great use of life is to spend it for something that will outlast it.", a: "William James" },
  { t: "Whatever the mind can conceive and believe, it can achieve.", a: "Napoleon Hill" },
  { t: "A goal is a dream with a deadline.", a: "Napoleon Hill" },
  { t: "Patience, persistence and perspiration make an unbeatable combination for success.", a: "Napoleon Hill" },
  { t: "Effort only fully releases its reward after a person refuses to quit.", a: "Napoleon Hill" },
  { t: "Strength and growth come only through continuous effort and struggle.", a: "Napoleon Hill" },
  { t: "The starting point of all achievement is desire.", a: "Napoleon Hill" },
  { t: "Don't count the days, make the days count.", a: "Muhammad Ali" },
  { t: "It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe.", a: "Muhammad Ali" },
  { t: "He who is not courageous enough to take risks will accomplish nothing in life.", a: "Muhammad Ali" },
  { t: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", a: "Muhammad Ali" },
  { t: "Impossible is just an opinion.", a: "Paulo Coelho" },
  { t: "When you want something, all the universe conspires in helping you to achieve it.", a: "Paulo Coelho" },
  { t: "The secret of life, though, is to fall seven times and to get up eight times.", a: "Paulo Coelho" },
  { t: "One is loved because one is loved. No reason is needed for loving.", a: "Paulo Coelho" },
  { t: "If you're going through hell, keep going.", a: "Winston Churchill" },
  { t: "Attitude is a little thing that makes a big difference.", a: "Winston Churchill" },
  { t: "To improve is to change; to be perfect is to change often.", a: "Winston Churchill" },
  { t: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", a: "Winston Churchill" },
  { t: "Success is stumbling from failure to failure with no loss of enthusiasm.", a: "Winston Churchill" },
  { t: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", a: "Winston Churchill" },
  { t: "Change your thoughts and you change your world.", a: "Norman Vincent Peale" },
  { t: "Shoot for the moon. Even if you miss, you'll land among the stars.", a: "Norman Vincent Peale" },
  { t: "Believe in yourself! Have faith in your abilities!", a: "Norman Vincent Peale" },
  { t: "The only way to achieve the impossible is to believe it is possible.", a: "Charles Kingsleigh" },
  { t: "You are never too old to reinvent yourself.", a: "Steve Harvey" },
  { t: "Hard work beats talent when talent doesn't work hard.", a: "Tim Notke" },
  { t: "Push yourself, because no one else is going to do it for you.", a: null },
  { t: "Great things never came from comfort zones.", a: null },
  { t: "Dream it. Wish it. Do it.", a: null },
  { t: "Success doesn't just find you. You have to go out and get it.", a: null },
  { t: "The harder you work for something, the greater you'll feel when you achieve it.", a: null },
  { t: "Dream bigger. Do bigger.", a: null },
  { t: "Don't stop when you're tired. Stop when you're done.", a: null },
  { t: "Wake up with determination. Go to bed with satisfaction.", a: null },
  { t: "Do something today that your future self will thank you for.", a: null },
  { t: "Little things make big days.", a: null },
  { t: "It's going to be hard, but hard does not mean impossible.", a: null },
  { t: "Don't wait for opportunity. Create it.", a: null },
  { t: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", a: null },
  { t: "The key to success is to focus on goals, not obstacles.", a: null },
  { t: "Dream it. Believe it. Build it.", a: null },
  { t: "Work hard in silence, let your success be your noise.", a: "Frank Ocean" },
  { t: "Don't limit your challenges. Challenge your limits.", a: null },
  { t: "Sometimes later becomes never. Do it now.", a: null },
  { t: "Success is the sum of small efforts repeated day in and day out.", a: "Robert Collier" },
  { t: "All progress takes place outside the comfort zone.", a: "Michael John Bobak" },
  { t: "You don't have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { t: "People often say that motivation doesn't last. Well, neither does bathing — that's why we recommend it daily.", a: "Zig Ziglar" },
  { t: "Your attitude, not your aptitude, will determine your altitude.", a: "Zig Ziglar" },
  { t: "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.", a: "Zig Ziglar" },
  { t: "Success is not in what you have, but who you are.", a: "Bo Bennett" },
  { t: "The distance between insanity and genius is measured only by success.", a: "Bruce Feirstein" },
  { t: "The road to success and the road to failure are almost exactly the same.", a: "Colin R. Davis" },
  { t: "Success is liking yourself, liking what you do, and liking how you do it.", a: "Maya Angelou" },
  { t: "The way to get started is to quit talking and begin doing.", a: "Walt Disney" },
  { t: "The successful person makes a habit of doing what the failing person doesn't like to do.", a: "Thomas Edison" },
  { t: "Don't let yesterday take up too much of today.", a: "Will Rogers" },
  { t: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", a: null },
  { t: "It's not whether you get knocked down, it's whether you get up.", a: "Vince Lombardi" },
  { t: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", a: "Steve Jobs" },
  { t: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { t: "Stay hungry, stay foolish.", a: "Steve Jobs" },
  { t: "Have the courage to follow your heart and intuition.", a: "Steve Jobs" },
  { t: "Sometimes life hits you in the head with a brick. Don't lose faith.", a: "Steve Jobs" },
  { t: "Great work is the result of not compromising.", a: "Steve Jobs" },
  { t: "The people who are crazy enough to think they can change the world are the ones who do.", a: "Steve Jobs" },
  { t: "Failure is simply the opportunity to begin again, this time more intelligently.", a: "Henry Ford" },
  { t: "Whether you think you can do a thing or think you can't, you are usually right.", a: "Henry Ford" },
  { t: "Coming together is a beginning; keeping together is progress; working together is success.", a: "Henry Ford" },
  { t: "Obstacles are those frightful things you see when you take your eyes off your goal.", a: "Henry Ford" },
  { t: "Anyone who stops learning is old, whether at twenty or eighty.", a: "Henry Ford" },
  { t: "You can't build a reputation on what you are going to do.", a: "Henry Ford" },
  { t: "Nothing is particularly hard if you divide it into small jobs.", a: "Henry Ford" },
  { t: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
  { t: "The man who will use his skill and constructive imagination to see how much he can give for a dollar, instead of how little, is bound to succeed.", a: "Henry Ford" },
  { t: "A goal properly set is halfway reached.", a: "Zig Ziglar" },
  { t: "Setting goals is the first step in turning the invisible into the visible.", a: "Tony Robbins" },
  { t: "The path to success is to take massive, determined action.", a: "Tony Robbins" },
  { t: "If you do what you've always done, you'll get what you've always gotten.", a: "Tony Robbins" },
  { t: "It is in your moments of decision that your destiny is shaped.", a: "Tony Robbins" },
  { t: "The only impossible journey is the one you never begin.", a: "Tony Robbins" },
  { t: "Where focus goes, energy flows.", a: "Tony Robbins" },
  { t: "Stay away from those people who try to disparage your ambitions.", a: "Mark Twain" },
  { t: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", a: "Mark Twain" },
  { t: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain" },
  { t: "Courage is resistance to fear, mastery of fear — not absence of fear.", a: "Mark Twain" },
  { t: "Continuous improvement is better than delayed perfection.", a: "Mark Twain" },
  { t: "Kindness is a language which the deaf can hear and the blind can see.", a: "Mark Twain" },
  { t: "Keep your face always toward the sunshine, and shadows will fall behind you.", a: "Walt Whitman" },
  { t: "We don't stop playing because we grow old; we grow old because we stop playing.", a: "George Bernard Shaw" },
  { t: "Life isn't about finding yourself. Life is about creating yourself.", a: "George Bernard Shaw" },
  { t: "People who say it cannot be done should not interrupt those who are doing it.", a: "George Bernard Shaw" },
  { t: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", a: "George Bernard Shaw" },
  { t: "The only thing we have to fear is fear itself.", a: "Franklin D. Roosevelt" },
  { t: "When you reach the end of your rope, tie a knot in it and hang on.", a: "Franklin D. Roosevelt" },
  { t: "Do one thing every day that scares you.", a: "Eleanor Roosevelt" },
  { t: "No one can make you feel inferior without your consent.", a: "Eleanor Roosevelt" },
  { t: "With the new day comes new strength and new thoughts.", a: "Eleanor Roosevelt" },
  { t: "You must do the things you think you cannot do.", a: "Eleanor Roosevelt" },
  { t: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", a: "Eleanor Roosevelt" },
  { t: "Happiness is not something ready made. It comes from your own actions.", a: "Dalai Lama" },
  { t: "Remember that not getting what you want is sometimes a wonderful stroke of luck.", a: "Dalai Lama" },
  { t: "Give the ones you love wings to fly, roots to come back, and reasons to stay.", a: "Dalai Lama" },
  { t: "The purpose of our lives is to be happy.", a: "Dalai Lama" },
  { t: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi" },
  { t: "Live as if you were to die tomorrow. Learn as if you were to live forever.", a: "Mahatma Gandhi" },
  { t: "The future depends on what you do today.", a: "Mahatma Gandhi" },
  { t: "Strength does not come from physical capacity. It comes from an indomitable will.", a: "Mahatma Gandhi" },
  { t: "In a gentle way, you can shake the world.", a: "Mahatma Gandhi" },
  { t: "First they ignore you, then they laugh at you, then they fight you, then you win.", a: "Mahatma Gandhi" },
  { t: "A person who never made a mistake never tried anything new.", a: "Albert Einstein" },
  { t: "The measure of intelligence is the ability to change.", a: "Albert Einstein" },
  { t: "Once we accept our limits, we go beyond them.", a: "Albert Einstein" },
  { t: "Weakness of attitude becomes weakness of character.", a: "Albert Einstein" },
  { t: "Learn from yesterday, live for today, hope for tomorrow.", a: "Albert Einstein" },
  { t: "Only those who dare to fail greatly can ever achieve greatly.", a: "Robert F. Kennedy" },
  { t: "Few will have the greatness to bend history itself, but each of us can work to change a small portion of events.", a: "Robert F. Kennedy" },
  { t: "The future belongs to those who prepare for it today.", a: "Malcolm X" },
  { t: "Education is our passport to the future, for tomorrow belongs to the people who prepare for it today.", a: "Malcolm X" },
  { t: "If you don't stand for something you'll fall for anything.", a: "Malcolm X" },
  { t: "A dream doesn't become reality through magic; it takes sweat, determination, and hard work.", a: "Colin Powell" },
  { t: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", a: "Colin Powell" },
  { t: "Success is the ability to go from one failure to another with no loss of enthusiasm.", a: "Winston Churchill" },
  { t: "The expert in anything was once a beginner.", a: "Helen Hayes" },
  { t: "You just can't beat the person who never gives up.", a: "Babe Ruth" },
  { t: "Every strike brings me closer to the next home run.", a: "Babe Ruth" },
  { t: "It's hard to beat a person who never gives up.", a: "Babe Ruth" },
  { t: "Champions keep playing until they get it right.", a: "Billie Jean King" },
  { t: "You have to believe in yourself when no one else does.", a: "Serena Williams" },
  { t: "Just don't give up trying to do what you really want to do.", a: "Ella Fitzgerald" },
  { t: "Do not let what you cannot do interfere with what you can do.", a: "John Wooden" },
  { t: "Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability.", a: "John Wooden" },
  { t: "Success is peace of mind which is a direct result of self-satisfaction in knowing you did your best.", a: "John Wooden" },
  { t: "It's the little details that are vital. Little things make big things happen.", a: "John Wooden" },
  { t: "Never mistake activity for achievement.", a: "John Wooden" },
  { t: "Things work out best for those who make the best of how things work out.", a: "John Wooden" },
  { t: "If you really look closely, most overnight successes took a long time.", a: "Steve Jobs" },
  { t: "The starting point of all achievement is desire. Keep this constantly in mind.", a: "Napoleon Hill" },
  { t: "Do the difficult things while they are easy and do the great things while they are small.", a: "Lao Tzu" },
  { t: "When I let go of what I am, I become what I might be.", a: "Lao Tzu" },
  { t: "A man who conquers himself is greater than one who conquers a thousand men in battle.", a: "Lao Tzu" },
  { t: "Nature does not hurry, yet everything is accomplished.", a: "Lao Tzu" },
  { t: "New beginnings are often disguised as painful endings.", a: "Lao Tzu" },
  { t: "The flower that blooms in adversity is the rarest and most beautiful of all.", a: "Walt Disney" },
  { t: "You define your own life. Don't let other people write your script.", a: "Oprah Winfrey" },
  { t: "The biggest adventure you can take is to live the life of your dreams.", a: "Oprah Winfrey" },
  { t: "Turn your wounds into wisdom.", a: "Oprah Winfrey" },
  { t: "Doing the best at this moment puts you in the best place for the next moment.", a: "Oprah Winfrey" },
  { t: "Passion is energy. Feel the power that comes from focusing on what excites you.", a: "Oprah Winfrey" },
  { t: "If you want to fly, give up everything that weighs you down.", a: "Buddha" },
  { t: "Your work is to discover your work and then with all your heart to give yourself to it.", a: "Buddha" },
  { t: "Just when the caterpillar thought the world was over, it became a butterfly.", a: null },
  { t: "The comeback is always stronger than the setback.", a: null },
  { t: "Stars can't shine without darkness.", a: null },
  { t: "Doubt kills more dreams than failure ever will.", a: "Suzy Kassem" },
  { t: "One day or day one. You decide.", a: null },
  { t: "Fear is temporary. Regret is forever.", a: null },
  { t: "The comfort zone is a beautiful place, but nothing ever grows there.", a: null },
  { t: "Discipline is choosing between what you want now and what you want most.", a: "Abraham Lincoln" },
  { t: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", a: "Abraham Lincoln" },
  { t: "The best way to predict your future is to create it.", a: "Abraham Lincoln" },
  { t: "Always bear in mind that your own resolution to succeed is more important than any other.", a: "Abraham Lincoln" },
  { t: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { t: "That which does not kill us makes us stronger.", a: "Friedrich Nietzsche" },
  { t: "He who has a why to live can bear almost any how.", a: "Friedrich Nietzsche" },
  { t: "The snake which cannot cast its skin has to die.", a: "Friedrich Nietzsche" },
  { t: "You must have chaos within you to give birth to a dancing star.", a: "Friedrich Nietzsche" },
  { t: "It is not the strongest of the species that survives, but the one most responsive to change.", a: "Charles Darwin" },
  { t: "A man who dares to waste one hour of time has not discovered the value of life.", a: "Charles Darwin" },
  { t: "We generate fears while we sit. We overcome them by action.", a: "Dr. Henry Link" },
  { t: "Someday is not a day of the week.", a: "Denise Brennan-Nelson" },
  { t: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", a: "Stephen King" },
  { t: "Talent is cheaper than table salt. What separates the talented from the successful is a lot of hard work.", a: "Stephen King" },
  { t: "You can, you should, and if you're brave enough to start, you will.", a: "Stephen King" },
  { t: "The scariest moment is always just before you start.", a: "Stephen King" },
  { t: "There is no elevator to success, you have to take the stairs.", a: "Zig Ziglar" },
  { t: "Fear defeats more people than any other one thing in the world.", a: "Ralph Waldo Emerson" },
  { t: "Finish each day and be done with it. You have done what you could.", a: "Ralph Waldo Emerson" },
  { t: "For every minute you are angry you lose sixty seconds of happiness.", a: "Ralph Waldo Emerson" },
  { t: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", a: "Ralph Waldo Emerson" },
  { t: "Adopt the pace of nature: her secret is patience.", a: "Ralph Waldo Emerson" },
  { t: "Do not wait; the time will never be 'just right.' Start where you stand.", a: "Napoleon Hill" },
  { t: "The ladder of success is never crowded at the top.", a: "Napoleon Hill" },
  { t: "Cherish your visions and your dreams, as they are the children of your soul.", a: "Napoleon Hill" },
  { t: "You become what you think about most of the time.", a: "Earl Nightingale" },
  { t: "We become what we think about.", a: "Earl Nightingale" },
  { t: "Success is the progressive realization of a worthy goal or ideal.", a: "Earl Nightingale" },
  { t: "Never give up, for that is just the place and time that the tide will turn.", a: "Harriet Beecher Stowe" },
  { t: "When you have a dream, you've got to grab it and never let go.", a: "Carol Burnett" },
  { t: "Believe you can and you're halfway there.", a: "Theodore Roosevelt" },
  { t: "Comparison is the thief of joy.", a: "Theodore Roosevelt" },
  { t: "Keep your eyes on the stars, and your feet on the ground.", a: "Theodore Roosevelt" },
  { t: "Nothing worth having comes easy.", a: "Theodore Roosevelt" },
  { t: "The credit belongs to the man who is actually in the arena.", a: "Theodore Roosevelt" },
  { t: "Everything you can imagine is real.", a: "Pablo Picasso" },
  { t: "Action is the foundational key to all success.", a: "Pablo Picasso" },
  { t: "Only put off until tomorrow what you are willing to die having left undone.", a: "Pablo Picasso" },
  { t: "The meaning of life is to find your gift. The purpose of life is to give it away.", a: "Pablo Picasso" },
  { t: "Inspiration exists, but it has to find you working.", a: "Pablo Picasso" },
  { t: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", a: "Mary Anne Radmacher" },
  { t: "What you do today can improve all your tomorrows.", a: "Ralph Marston" },
  { t: "Excellence is to do a common thing in an uncommon way.", a: "Booker T. Washington" },
  { t: "Success is to be measured not so much by the position that one has reached in life as by the obstacles overcome.", a: "Booker T. Washington" },
  { t: "The best preparation for tomorrow is doing your best today.", a: "H. Jackson Brown Jr." },
  { t: "Nothing is impossible. The word itself says 'I'm possible!'", a: "Audrey Hepburn" },
  { t: "For beautiful eyes, look for the good in others.", a: "Audrey Hepburn" },
  { t: "As long as you're going to be thinking anyway, think big.", a: "Donald Trump" },
  { t: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", a: "Johann Wolfgang von Goethe" },
  { t: "Knowing is not enough; we must apply. Willing is not enough; we must do.", a: "Johann Wolfgang von Goethe" },
  { t: "Just trust yourself, then you will know how to live.", a: "Johann Wolfgang von Goethe" },
  { t: "It is not enough to have knowledge, one must also apply it.", a: "Johann Wolfgang von Goethe" },
  { t: "Everything in the universe has a rhythm, everything dances.", a: "Maya Angelou" },
  { t: "You have within you right now, everything you need to deal with whatever the world can throw at you.", a: "Brian Tracy" },
  { t: "Successful people are always looking for opportunities to help others.", a: "Brian Tracy" },
  { t: "Move out of your comfort zone. You can only grow if you are willing to feel awkward.", a: "Brian Tracy" },
  { t: "The key to success is to focus our conscious mind on things we desire, not things we fear.", a: "Brian Tracy" },
  { t: "Never let your fear decide your future.", a: null },
  { t: "Difficult roads often lead to beautiful destinations.", a: null },
  { t: "Be so good they can't ignore you.", a: "Steve Martin" },
  { t: "Fortune favors the bold.", a: "Virgil" },
  { t: "The best view comes after the hardest climb.", a: null },
  { t: "Rise up, start fresh, see the bright opportunity in each new day.", a: null },
  { t: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", a: "Roy T. Bennett" },
  { t: "Accept the challenges so that you can feel the exhilaration of victory.", a: "George S. Patton" },
  { t: "Do not fear failure but rather fear not trying.", a: "Roy T. Bennett" },
  { t: "If you cannot do great things, do small things in a great way.", a: "Napoleon Hill" },
  { t: "Focus on being productive instead of busy.", a: "Tim Ferriss" },
  { t: "What we fear doing most is usually what we most need to do.", a: "Tim Ferriss" },
  { t: "A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.", a: "Tim Ferriss" },
  { t: "Someday is a disease that will take your dreams to the grave with you.", a: "Tim Ferriss" },
  { t: "The person who says it cannot be done should not interrupt the person doing it.", a: "Chinese Proverb" },
  { t: "A bend in the road is not the end of the road… unless you fail to make the turn.", a: "Helen Keller" },
  { t: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", a: "Helen Keller" },
  { t: "Life is either a daring adventure or nothing at all.", a: "Helen Keller" },
  { t: "Keep your face to the sunshine and you cannot see a shadow.", a: "Helen Keller" },
  { t: "Alone we can do so little; together we can do so much.", a: "Helen Keller" },
  { t: "The only thing worse than being blind is having sight but no vision.", a: "Helen Keller" },
  { t: "When one door of happiness closes, another opens.", a: "Helen Keller" },
  { t: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", a: "Helen Keller" },
  { t: "You are enough just as you are.", a: null },
  { t: "Progress, not perfection.", a: null },
  { t: "Slow progress is still progress.", a: null },
  { t: "Discipline equals freedom.", a: "Jocko Willink" },
  { t: "Don't expect to be motivated every day to get out there and make things happen. You won't be. Don't count on motivation. Count on discipline.", a: "Jocko Willink" },
  { t: "The only easy day was yesterday.", a: "Navy SEALs" },
  { t: "Get comfortable being uncomfortable.", a: null },
  { t: "You didn't come this far to only come this far.", a: null },
  { t: "Small steps every day.", a: null },
  { t: "Fall in love with the process and the results will come.", a: "Eric Thomas" },
  { t: "When you want to succeed as bad as you want to breathe, then you'll be successful.", a: "Eric Thomas" },
  { t: "Pain is temporary. It may last a minute, or an hour, or a day, but eventually it will subside.", a: "Lance Armstrong" },
  { t: "It's not about perfect. It's about effort.", a: "Jillian Michaels" },
  { t: "You can waste your lives drawing lines. Or you can live your life crossing them.", a: "Shonda Rhimes" },
  { t: "Do what you feel in your heart to be right, for you'll be criticized anyway.", a: "Eleanor Roosevelt" },
  { t: "If you want to go fast, go alone. If you want to go far, go together.", a: "African Proverb" },
  { t: "Smooth seas do not make skillful sailors.", a: "African Proverb" },
  { t: "However difficult life may seem, there is always something you can do and succeed at.", a: "Stephen Hawking" },
  { t: "Intelligence is the ability to adapt to change.", a: "Stephen Hawking" },
  { t: "Look up at the stars and not down at your feet.", a: "Stephen Hawking" },
  { t: "Perseverance is not a long race; it is many short races one after the other.", a: "Walter Elliot" },
  { t: "Success seems to be connected with action. Successful people keep moving.", a: "Conrad Hilton" },
  { t: "Try to be a rainbow in someone's cloud.", a: "Maya Angelou" },
  { t: "The harder you work, the luckier you get.", a: "Gary Player" },
  { t: "A little progress each day adds up to big results.", a: null },
  { t: "Your only limit is you.", a: null },
  { t: "Be stubborn about your goals and flexible about your methods.", a: null },
  { t: "Prove them wrong.", a: null },
  { t: "Great dreams of great dreamers are always transcended.", a: "A.P.J. Abdul Kalam" },
  { t: "If you want to shine like a sun, first burn like a sun.", a: "A.P.J. Abdul Kalam" },
  { t: "You have to dream before your dreams can come true.", a: "A.P.J. Abdul Kalam" },
  { t: "Don't take rest after your first victory because if you fail in second, more lips are waiting to say that your first victory was just luck.", a: "A.P.J. Abdul Kalam" },
  { t: "Man needs his difficulties because they are necessary to enjoy success.", a: "A.P.J. Abdul Kalam" },
  { t: "All the power is within you; you can do anything and everything.", a: "Swami Vivekananda" },
  { t: "Arise, awake, and stop not until the goal is reached.", a: "Swami Vivekananda" },
  { t: "Take up one idea. Make that one idea your life.", a: "Swami Vivekananda" },
  { t: "In a day, when you don't come across any problems — you can be sure that you are traveling in a wrong path.", a: "Swami Vivekananda" },
];
